"""Add verification and links to Cafe

Revision ID: 91e1924edcae
Revises: 91fa4dc21678
Create Date: 2026-03-21 21:01:10.889684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e1924edcae'
down_revision: Union[str, Sequence[str], None] = '91fa4dc21678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafes', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('cafes', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('cafes', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafes', 'is_verified')
    op.drop_column('cafes', 'instagram_url')
    op.drop_column('cafes', 'website_url')
    # ### end Alembic commands ###
