"""Add proof_of_work to missions

Revision ID: 91fa4dc21678
Revises: ed5f32d1dabd
Create Date: 2026-01-31 01:41:42.103177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91fa4dc21678'
down_revision: Union[str, Sequence[str], None] = 'ed5f32d1dabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('proof_of_work', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'proof_of_work')
    # ### end Alembic commands ###
